variable "stack_description" {}
variable "rds_instance_type" {}
variable "rds_db_size" {}
variable "rds_db_name" {}
variable "rds_db_engine" {}
variable "rds_db_engine_version" {}
variable "rds_username" {}
variable "rds_password" {}
variable "rds_subnet_group" {}
variable "rds_security_groups" {}
